Feature/milestone 2.1
eliasecasta/bookstore pull request #2
Opened 2021-04-21 15:57 UTC by Lidya1234

-Added a table for displaying books
-Added a form for adding books
-Created all the necessary files required for the project
-We made use of the redux-toolkit library in this project instead of vanilla redux because it is simpler, more powerful, and newer. Some file locations might change but the concept keeps being the same. Please take this into account when checking the code.

2021-04-21 17:22 UTC, uche-inyama requested changes
## Changes Required

### Hi team :wave: 

We need to restructure our files and make little modifications.

* [ ] Booklist and bookform components should be moved to src/container directory.
* [ ] There are two app.js files in your project. One is in the root directory and the other in the component folder; delete one of them.
* [ ] Book component should be imported and rendered in Booklist component. 
* [ ] In the booklist component, the instance of the book component rendered should receive 
 book object as prop.

That's it make these changes, then submit another form for a code review.

#### If there is a need for clarifications, kindly reach out on slack @ Inyama, Uchechukwu Henry.

### Happy coding :technologist: 

#### ``` Uchechukwu Henry Inyama ```

2021-04-21 17:22 UTC, uche-inyama commented on src/components/BooksList.js
> +    </table>
This component should look like so:
``` 
 <table>
      <thead>
        <tr>
          <th>ID</th>
          <th>Title</th>
          <th>Category</th>
        </tr>
      </thead>
      <tbody>
        {books.map((book) => (
          <Book key={book.id} book={book} />
        ))}
      </tbody>
    </table>
```

2021-04-21 17:22 UTC, uche-inyama commented on src/components/Book.js
> +export default Book;
This is how the book component should look like.
```

const Book = ({ book: { id, title, category } }) => (
  <tr>
    <td>{id}</td>
    <td>{title}</td>
    <td>{category}</td>
  </tr>
);
```

2021-04-22 11:33 UTC, bellom approved these changes
## Hi @Lidya1234  :clap: 

**Great work making all the necessary corrections from the previous review.**

# Status: Approved 👍 

## Congratulation :+1:  
_Go ahead and merge to dev and don't forget to submit the project completion form.
Good luck in the next milestone :slightly_smiling_face:_ 

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2021-04-22 15:47 UTC, merged